  
# Azure DevOps Pipeline that Run PR to enable branching policies in GitHub Enterprise


trigger:
- Main

pr:
- Main

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPR: $[eq(variables['Build.Reason'], 'PullRequest']

stages:
- stage: Continous Intergration
  jobs: 
  - job: CI-PR-Buld-Validation
    condition: and(succeeded(), eq(variables.isPR, true))
    pool:
      vmImage:"ubuntu-latest"
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: 'echo "Run PR Validation Steps"'
        failOnStderr: false
  - job: CI-Build
    condition: and(succeeded(), eq(variables.isMain, true))
    pool:
      vmImage:"ubuntu-latest"
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: 'echo "Run build Artifact steps"'
        failOnStderr: false

- stage: Continous Deployment - Production
  jobs: 
  - job: "CD-Production"
    condition: and(succeeded(), eq(variables.isMain, true))
    pool:
      vmImage:"ubuntu-latest"
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: 'echo "Deploy to Production"'
        failOnStderr: false